#ifndef SPIRAL_HPP
#define SPIRAL_HPP

#include "Core/MemoryOperators.hpp"
#include "Core/Sp_DataTypes.hpp"
#include "Core/Application.hpp"
#include "Core/Engine.hpp"
#include "Core/GameState.hpp"
#include "Core/Event.hpp"
#include "Core/Events.hpp"
#include "Core/EventSubscriber.hpp"
#include "COre/EventPublisher.hpp"
#include "Core/FileManager.hpp"
#include "Core/File.hpp"
#include "Core/Camera.hpp"
#include "Core/TypeUtils.hpp"
#include "Core/EngineAttributes.hpp"
#include "Core/Log.hpp"

#include "Gfx/Color.hpp"
#include "Gfx/GfxDriver.hpp"
#include "Gfx/Geometry.hpp"
#include "Gfx/GeometryType.hpp"
#include "Gfx/GfxImpl.hpp"
#include "Gfx/Material.hpp"
#include "Gfx/VertexBuffer.hpp"
#include "Gfx/IndexBuffer.hpp"
#include "Gfx/VertexFormatImpl.hpp"
#include "Gfx/IndexFormatImpl.hpp"
#include "Gfx/RenderState.hpp"
#include "Gfx/Utility/Image.hpp"
#include "Gfx/Projection.hpp"
#include "Gfx/Sprite.hpp"
#include "Gfx/Font.hpp"
#include "Gfx/Surface.hpp"

#include "Gfx/gui/GuiWindow.hpp"
#include "Gfx/gui/GuiButton.hpp"
#include "Gfx/gui/Gui.hpp"
#include "Gfx/gui/GuiWindowEvents.hpp"
#include "Gfx/gui/GuiEditBox.hpp"
#include "Gfx/gui/GuiText.hpp"
#include "Gfx/gui/GuiCheckBox.hpp"
#include "Gfx/gui/GuiSlider.hpp"

#endif